tools:
  exceptions:
    frontend: https://dcsil.sentry.io/projects/ezra-mvp-frontend/?project=4504776458698752
    backend: https://dcsil.sentry.io/projects/ezra-mvp-backend/?project=4504776538324992
  logging: 
  ci: https://github.com/dcsil/ezraFitMVP/blob/main/.github/workflows/githubActionsNode.yml

services:
  production:
    frontend: https://ezrafit.onrender.com/
    backend: https://ezrafit-backend.onrender.com/ 

docs:
  getting_started: https://github.com/dcsil/ezra

commands:
  bootstrap: sh script/bootstrap
  database: ''
  server: 
    frontend: cd frontend; npm start
    backend: cd backend; python3 app.py
  test: cd frontend; npm test