name: EzraFit Node.js CI
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Add this line here
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
      - name: Run frontend
        working-directory: ./frontend
        run: |
            npm ci
            npm test
