name: EzraFit Node.js CI
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Add this line here
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
      - name: Run frontend
        working-directory: ./frontend
        run: |
            npm ci
            npm test
  
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
#       
      - name: Test coverage frontend
        run: |
            cd frontend
            npm ci
            npm test
      
      - name: Upload CC
        working-directory: ./frontend
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: npm run coverage
          coverageLocations: |
            ${{github.workspace}}/frontend/coverage/lcov.info:lcov


  