name: EzraFit Node.js CI
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Add this line here
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
      - name: Run frontend
        working-directory: ./frontend
        run: |
            npm ci
            npm test
  
  tests:
    name: "Tests (${{ matrix.os.os-label }})"
    strategy:
      matrix:
        os:
          - { index: 1, os-name: 'ubuntu-latest', os-label: 'Linux' }
          - { index: 2, os-name: 'macos-latest', os-label: 'macOS' }
    runs-on: ${{ matrix.os.os-name }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install dependencies
      working-directory: ./frontend
      run: npm ci

    - name: run tests and instrument coverage
      run: npm run coverage

    - name: publish code coverage to code-climate (duh)
      if: ${{ github.event_name == 'push' && matrix.os.index == 1 }} # Push coverage only once inside the matrix.
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: 1b6106874f51e674209d8804a115173e144ec375da5489ec4867f0a9dac41eed
      with:
        debug: true