name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
      - name: Run frontend
        working-directory: ../frontend
        run: |
            npm start
      - run: echo "This job's status is ${{ job.status }}."
